namespace TetrisLogic
{
	partial class GameCanvas
	{
		/// <summary>
		/// Window components
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Dispose window
		/// </summary>
		/// <param name="disposing"></param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

        #region Code Automatically Generated by Component Designer

        /// <summary> 
        /// Initialize window components
        /// </summary>
        private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			this.timer = new System.Windows.Forms.Timer(this.components);
			this.SuspendLayout();
			// 
			// timer
			// 
			this.timer.Interval = 1;
			this.timer.Tick += new System.EventHandler(this.Timer_Tick);
			// 
			// GameCanvas
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.DoubleBuffered = true;
			this.Name = "GameCanvas";
			this.Size = new System.Drawing.Size(390, 700);
			this.Load += new System.EventHandler(this.GameCanvas_Load);
			this.Click += new System.EventHandler(this.GameCanvas_Click);
			this.Paint += new System.Windows.Forms.PaintEventHandler(this.GameCanvas_Paint);
			this.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.GameCanvas_KeyPress);
			this.KeyUp += new System.Windows.Forms.KeyEventHandler(this.GameCanvas_KeyUp);
			this.MouseMove += new System.Windows.Forms.MouseEventHandler(this.GameCanvas_MouseMove);
			this.ResumeLayout(false);
		}

		#endregion

		private System.Windows.Forms.Timer timer;
	}
}
